// <auto-generated />
using System;
using HoshiVibe.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HoshiVibe.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251112025749_AddCustomDesignEntity")]
    partial class AddCustomDesignEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HoshiVibe.Entities.Models.Base.Cart", b =>
                {
                    b.Property<Guid>("Cart_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("User_Id")
                        .HasColumnType("uuid");

                    b.HasKey("Cart_Id");

                    b.HasIndex("User_Id")
                        .IsUnique();

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("HoshiVibe.Entities.Models.Base.CartItem", b =>
                {
                    b.Property<Guid>("CartItem_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("Cart_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("Product_Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("CartItem_Id");

                    b.HasIndex("Cart_Id");

                    b.HasIndex("Product_Id");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("HoshiVibe.Entities.Models.Base.CustomDesign", b =>
                {
                    b.Property<Guid>("CustomDesign_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiImageUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OrderDetailsOrderDetail_Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("RawImageBase64")
                        .HasColumnType("text");

                    b.Property<Guid?>("User_Id")
                        .HasColumnType("uuid");

                    b.HasKey("CustomDesign_Id");

                    b.HasIndex("OrderDetailsOrderDetail_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("CustomDesigns");
                });

            modelBuilder.Entity("HoshiVibe.Entities.Models.Base.CustomDesignCharm", b =>
                {
                    b.Property<Guid>("CustomDesignCharm_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CProduct_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomDesign_Id")
                        .HasColumnType("uuid");

                    b.HasKey("CustomDesignCharm_Id");

                    b.HasIndex("CProduct_Id");

                    b.HasIndex("CustomDesign_Id");

                    b.ToTable("CustomDesignCharms");
                });

            modelBuilder.Entity("HoshiVibe.Entities.Models.Base.CustomProduct", b =>
                {
                    b.Property<Guid>("CProduct_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<Guid?>("OrderDetailsOrderDetail_Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid?>("User_Id")
                        .HasColumnType("uuid");

                    b.HasKey("CProduct_Id");

                    b.HasIndex("OrderDetailsOrderDetail_Id");

                    b.HasIndex("User_Id");

                    b.ToTable("CustomProduct", (string)null);
                });

            modelBuilder.Entity("HoshiVibe.Entities.Models.Base.Destiny", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Destinies");
                });

            modelBuilder.Entity("HoshiVibe.Entities.Models.Base.Order", b =>
                {
                    b.Property<string>("Order_Id")
                        .HasColumnType("text");

                    b.Property<Guid?>("Cart_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CustomProductCProduct_Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("FinalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PhoneNumber")
                        .HasColumnType("integer");

                    b.Property<string>("ShippingAddress")
                        .HasColumnType("text");

                    b.Property<string>("ShippingStatus")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("User_Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Voucher_Id")
                        .HasColumnType("uuid");

                    b.HasKey("Order_Id");

                    b.HasIndex("Cart_Id");

                    b.HasIndex("CustomProductCProduct_Id");

                    b.HasIndex("User_Id");

                    b.HasIndex("Voucher_Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("HoshiVibe.Entities.Models.Base.OrderDetail", b =>
                {
                    b.Property<Guid>("OrderDetail_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CProduct_Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Discount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("Product_Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("OrderDetail_Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("Product_Id");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("HoshiVibe.Entities.Models.Base.Payment", b =>
                {
                    b.Property<Guid>("Payment_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Order_Id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Payment_Id");

                    b.HasIndex("Order_Id")
                        .IsUnique();

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("HoshiVibe.Entities.Models.Base.PaymentTransactions", b =>
                {
                    b.Property<Guid>("Transaction_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("GatewayTransactionId")
                        .HasColumnType("integer");

                    b.Property<Guid>("Payment_Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Transaction_Id");

                    b.HasIndex("Payment_Id");

                    b.ToTable("PaymentTransactions");
                });

            modelBuilder.Entity("HoshiVibe.Entities.Models.Base.Product", b =>
                {
                    b.Property<Guid>("Product_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Destiny")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("Product_Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("HoshiVibe.Entities.Models.Base.User", b =>
                {
                    b.Property<Guid>("User_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("resetToken")
                        .HasColumnType("text");

                    b.HasKey("User_Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HoshiVibe.Entities.Models.Base.UserProfile", b =>
                {
                    b.Property<Guid>("UserProfile_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<int?>("DestinyId")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Point")
                        .HasColumnType("integer");

                    b.Property<Guid>("User_Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Yob")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("YobDestination")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ZodiacId")
                        .HasColumnType("integer");

                    b.HasKey("UserProfile_Id");

                    b.HasIndex("DestinyId");

                    b.HasIndex("User_Id")
                        .IsUnique();

                    b.HasIndex("ZodiacId");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("HoshiVibe.Entities.Models.Base.Voucher", b =>
                {
                    b.Property<Guid>("Voucher_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UseTime")
                        .HasColumnType("integer");

                    b.Property<int>("UsedCount")
                        .HasColumnType("integer");

                    b.Property<string>("VoucherName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Voucher_Id");

                    b.ToTable("Vouchers");
                });

            modelBuilder.Entity("HoshiVibe.Entities.Models.Base.Zodiac", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Zodiacs");
                });

            modelBuilder.Entity("HoshiVibe.Entities.Models.Base.Cart", b =>
                {
                    b.HasOne("HoshiVibe.Entities.Models.Base.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("HoshiVibe.Entities.Models.Base.Cart", "User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HoshiVibe.Entities.Models.Base.CartItem", b =>
                {
                    b.HasOne("HoshiVibe.Entities.Models.Base.Cart", "Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("Cart_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HoshiVibe.Entities.Models.Base.Product", "Product")
                        .WithMany()
                        .HasForeignKey("Product_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("HoshiVibe.Entities.Models.Base.CustomDesign", b =>
                {
                    b.HasOne("HoshiVibe.Entities.Models.Base.OrderDetail", "OrderDetails")
                        .WithMany()
                        .HasForeignKey("OrderDetailsOrderDetail_Id");

                    b.HasOne("HoshiVibe.Entities.Models.Base.User", "User")
                        .WithMany()
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("OrderDetails");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HoshiVibe.Entities.Models.Base.CustomDesignCharm", b =>
                {
                    b.HasOne("HoshiVibe.Entities.Models.Base.CustomProduct", "Charm")
                        .WithMany("CustomDesignCharms")
                        .HasForeignKey("CProduct_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HoshiVibe.Entities.Models.Base.CustomDesign", "CustomDesign")
                        .WithMany("CustomDesignCharms")
                        .HasForeignKey("CustomDesign_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Charm");

                    b.Navigation("CustomDesign");
                });

            modelBuilder.Entity("HoshiVibe.Entities.Models.Base.CustomProduct", b =>
                {
                    b.HasOne("HoshiVibe.Entities.Models.Base.OrderDetail", "OrderDetails")
                        .WithMany()
                        .HasForeignKey("OrderDetailsOrderDetail_Id");

                    b.HasOne("HoshiVibe.Entities.Models.Base.User", "User")
                        .WithMany()
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("OrderDetails");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HoshiVibe.Entities.Models.Base.Order", b =>
                {
                    b.HasOne("HoshiVibe.Entities.Models.Base.Cart", "Cart")
                        .WithMany()
                        .HasForeignKey("Cart_Id");

                    b.HasOne("HoshiVibe.Entities.Models.Base.CustomProduct", "CustomProduct")
                        .WithMany()
                        .HasForeignKey("CustomProductCProduct_Id");

                    b.HasOne("HoshiVibe.Entities.Models.Base.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("User_Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HoshiVibe.Entities.Models.Base.Voucher", "Voucher")
                        .WithMany("Orders")
                        .HasForeignKey("Voucher_Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cart");

                    b.Navigation("CustomProduct");

                    b.Navigation("User");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("HoshiVibe.Entities.Models.Base.OrderDetail", b =>
                {
                    b.HasOne("HoshiVibe.Entities.Models.Base.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HoshiVibe.Entities.Models.Base.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HoshiVibe.Entities.Models.Base.Product", null)
                        .WithMany("OrderDetails")
                        .HasForeignKey("Product_Id");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("HoshiVibe.Entities.Models.Base.Payment", b =>
                {
                    b.HasOne("HoshiVibe.Entities.Models.Base.Order", "Order")
                        .WithOne("Payment")
                        .HasForeignKey("HoshiVibe.Entities.Models.Base.Payment", "Order_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("HoshiVibe.Entities.Models.Base.PaymentTransactions", b =>
                {
                    b.HasOne("HoshiVibe.Entities.Models.Base.Payment", "Payment")
                        .WithMany("Transactions")
                        .HasForeignKey("Payment_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("HoshiVibe.Entities.Models.Base.UserProfile", b =>
                {
                    b.HasOne("HoshiVibe.Entities.Models.Base.Destiny", "Destiny")
                        .WithMany("UserProfiles")
                        .HasForeignKey("DestinyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HoshiVibe.Entities.Models.Base.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("HoshiVibe.Entities.Models.Base.UserProfile", "User_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HoshiVibe.Entities.Models.Base.Zodiac", "Zodiac")
                        .WithMany("UserProfiles")
                        .HasForeignKey("ZodiacId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Destiny");

                    b.Navigation("User");

                    b.Navigation("Zodiac");
                });

            modelBuilder.Entity("HoshiVibe.Entities.Models.Base.Cart", b =>
                {
                    b.Navigation("CartItems");
                });

            modelBuilder.Entity("HoshiVibe.Entities.Models.Base.CustomDesign", b =>
                {
                    b.Navigation("CustomDesignCharms");
                });

            modelBuilder.Entity("HoshiVibe.Entities.Models.Base.CustomProduct", b =>
                {
                    b.Navigation("CustomDesignCharms");
                });

            modelBuilder.Entity("HoshiVibe.Entities.Models.Base.Destiny", b =>
                {
                    b.Navigation("UserProfiles");
                });

            modelBuilder.Entity("HoshiVibe.Entities.Models.Base.Order", b =>
                {
                    b.Navigation("OrderDetails");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("HoshiVibe.Entities.Models.Base.Payment", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("HoshiVibe.Entities.Models.Base.Product", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("HoshiVibe.Entities.Models.Base.User", b =>
                {
                    b.Navigation("Cart");

                    b.Navigation("Orders");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("HoshiVibe.Entities.Models.Base.Voucher", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("HoshiVibe.Entities.Models.Base.Zodiac", b =>
                {
                    b.Navigation("UserProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
